# Generated by Django 5.0 on 2024-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_id', models.IntegerField(unique=True)),
                ('passengers', models.IntegerField(default=0)),
            ],
        ),
    ]
